In [ ]:
#1. Initialize an empty array with size 2X2.
import numpy as np

empty_array = np.empty((2, 2))
print(empty_array)

#2. Initialize an all one array with size 4X2.
import numpy as np

ones_array = np.ones((4, 2))
print(ones_array)

#3.Return a new array of given shape and type, filled with fill value.{Hint: np.full}
import numpy as np
full_array = np.full((3, 3), fill_value=7, dtype=int)
print(full_array)

#4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print(zeros_like_array)

#5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print(ones_like_array)

#6. Convert an existing list to numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print( numpy_array)


[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("1.\n", array_10_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2.\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3.\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4.\n", random_array)
print("Mean of the array:", mean_value)

# 5. Create a 10x10 array with random values and find min and max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5.\n", random_10x10)
print("Min:", min_value, "Max:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6.\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7.\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
n, m = 5, 5
border_array = np.ones((n, m))
border_array[1:-1, 1:-1] = 0
print("\n8.\n", border_array)

# 9. Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:\n", checkerboard)


1.
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2.
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3.
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4.
 [0.83811942 0.98599619 0.92089484 0.70342595 0.59192913 0.75231751
 0.1628169  0.83907405 0.29845527 0.45438584 0.20441271 0.59161585
 0.03093417 0.8029292  0.73433664 0.29970394 0.27331321 0.19042026
 0.59204692 0.68942656 0.44238841 0.99881135 0.25563861 0.71932122
 0.19934279 0.58320415 0.70513897 0.40734519 0.53613512 0.11403359]
Mean of the array: 0.5305971321747016

5.
 [[0.96318083 0.90706582 0.11361432 0.2775057  0.12076797 0.27576493
  0.6566722  0.24007718 0.63258583 0.76029327]
 [0.33102228 0.66981777 0.03271356 0.59104518 0.79109315 0.30910747
  0.64210655 0.78236403 0.83919969 0.65879003]
 [0.95557071 0.10535928 0.26619672 0.80868227 0.55840669 0.86142275
  0.3256627  0.90885496 0.74265124 0.2470924 ]
 [0.48651277 0.85138613 0.61423465 0.7748419  0.7700519  0.7084032
  

In [2]:
import numpy as np

# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("1.(x + y):")
print(x + y)

print("\n2.(x - y):")
print(x - y)

print("\n3.(3 * x):")
print(3 * x)

print("\n4.(x**2):")
print(x**2)

print("\n5(a). Dot product of v.w:")
print(np.dot(v, w))

print("\n5(b). Dot product of x.v:")
print(np.dot(x, v))

print("\n5(c). Dot product of x .y:")
print(np.dot(x, y))

print("\n6(a). Concatenate x and y along rows:")
print(np.vstack((x, y)))

print("\n6(b). Concatenate v and w along columns:")
print(np.column_stack((v, w)))

print("\n7. Concatenate x and v (Shows error explanation):")
try:
    print(np.concatenate((x, v)))
except Exception as e:
    print("Error:", e)
    print("Reason: x is 2D but v is 1D. NumPy cannot concatenate arrays with different dimensions.")


1.(x + y):
[[ 6  8]
 [10 13]]

2.(x - y):
[[-4 -4]
 [-4 -3]]

3.(3 * x):
[[ 3  6]
 [ 9 15]]

4.(x**2):
[[ 1  4]
 [ 9 25]]

5(a). Dot product of v.w:
219

5(b). Dot product of x.v:
[29 77]

5(c). Dot product of x .y:
[[19 22]
 [50 58]]

6(a). Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

6(b). Concatenate v and w along columns:
[[ 9 11]
 [10 12]]

7. Concatenate x and v (Shows error explanation):
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D but v is 1D. NumPy cannot concatenate arrays with different dimensions.


In [4]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# 1.
A_inv = np.linalg.inv(A)
I = A.dot(A_inv)

print("\n1. A * A^{-1} = I:",I)
print("Is Identity (approx)?", np.allclose(I, np.eye(2)))


# 2. Prove AB != BA
AB = A.dot(B)
BA = B.dot(A)

print("\n2. AB:\n", AB)
print("\n   BA:\n", BA)
print("\nIs AB = BA?", np.array_equal(AB, BA))


# 3.
LHS = (AB).T
RHS = B.T.dot(A.T)

print("\n3. (AB)^T:\n", LHS)
print("\n   B^T A^T:\n", RHS)
print("\nIs (AB)^T = B^T A^T ?", np.allclose(LHS, RHS))


# PART 2: SOLVE SYSTEM OF EQUATIONS
# System:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

A2 = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3,  1, -1]
])

B2 = np.array([-1, -3, 9])

print("\n\nSystem of Equations in Matrix Form:")
print("A =\n", A2)
print("B =\n", B2)

# Solve using inverse method: X = A^{-1} B
A2_inv = np.linalg.inv(A2)
X_solution = A2_inv.dot(B2)

print("\nSolution using Inverse Method (X = A^{-1}B):")
print("x, y, z =", X_solution)


# ---------------------------------------
# PART 3: Solve using numpy.linalg.solve
# ---------------------------------------

X_solve = np.linalg.solve(A2, B2)

print("\nSolution using np.linalg.solve:")
print("x, y, z =", X_solve)

# Check if both methods match
print("\nDo both solutions match?", np.allclose(X_solution, X_solve))


Matrix A:
 [[3 4]
 [7 8]]
Matrix B:
 [[5 3]
 [2 1]]

1. A * A^{-1} = I: [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is Identity (approx)? True

2. AB:
 [[23 13]
 [51 29]]

   BA:
 [[36 44]
 [13 16]]

Is AB = BA? False

3. (AB)^T:
 [[23 51]
 [13 29]]

   B^T A^T:
 [[23 51]
 [13 29]]

Is (AB)^T = B^T A^T ? True


System of Equations in Matrix Form:
A =
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
B =
 [-1 -3  9]

Solution using Inverse Method (X = A^{-1}B):
x, y, z = [ 2.  1. -2.]

Solution using np.linalg.solve:
x, y, z = [ 2.  1. -2.]

Do both solutions match? True


In [ ]:
# TASK 4.2.1

import time
import numpy as np

print("1. ELEMENT-WISE ADDITION")

# Python list addition
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Addition Time:", end - start, "seconds")

# NumPy addition
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start, "seconds")


print("\n2. ELEMENT-WISE MULTIPLICATION")

# Python list multiplication
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Multiplication Time:", end - start, "seconds")

# NumPy multiplication
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start, "seconds")


print("\n3. DOT PRODUCT")

# Python list dot product
start = time.time()
dot_py = sum(list1[i] * list2[i] for i in range(1_000_000))
end = time.time()
print("Python List Dot Product Time:", end - start, "seconds")

# NumPy dot product
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy Dot Product Time:", end - start, "seconds")


print("\n4. MATRIX MULTIPLICATION (1000 x 1000)")

# Python list matrix multiplication
matrix1 = [[1]*1000 for _ in range(1000)]
matrix2 = [[1]*1000 for _ in range(1000)]

start = time.time()
result_matrix = [
    [sum(matrix1[i][k] * matrix2[k][j] for k in range(1000))
    for j in range(1000)]
    for i in range(1000)
]
end = time.time()
print("Python List Matrix Multiplication Time:", end - start, "seconds")

# NumPy matrix multiplication
np_matrix1 = np.ones((1000, 1000))
np_matrix2 = np.ones((1000, 1000))

start = time.time()
np_result = np.dot(np_matrix1, np_matrix2)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start, "seconds")


1. ELEMENT-WISE ADDITION
Python List Addition Time: 0.11789822578430176 seconds
NumPy Array Addition Time: 0.004347085952758789 seconds

2. ELEMENT-WISE MULTIPLICATION
Python List Multiplication Time: 0.11649084091186523 seconds
NumPy Array Multiplication Time: 0.00536656379699707 seconds

3. DOT PRODUCT
Python List Dot Product Time: 0.10214924812316895 seconds
NumPy Dot Product Time: 0.001920461654663086 seconds

4. MATRIX MULTIPLICATION (1000 x 1000)
